### ISSUE TITLE
Trouble downloading data directly to server

### ISSUE THREAD

**Issue by rlittman16** [linnarsson-lab/adult-human-brain#2]
Thanks for generating this dataset! It is really nice!

I was trying to download the data and gdsk wasn't working and neither does wget. I can click on the link and have the download to start but I'd rather not download the data locally and upload as it is >60Gb. 

Any ideas?

**Comment by ccruizm** [comment]
Hello!

Do not copy the link from GitHub but from the google storage cloud. Here it is `wget https://storage.googleapis.com/linnarsson-lab-human/adult_human_20221007.loom`. This worked for me.

**Comment by rlittman16** [comment]
This worked. Thanks!

**Comment by rmd13** [comment]
I use my cellphone to download it from GitHub link.
It takes overnight with speed of 2Mb~5Mb/s. If failed for the first night, but the second night it succeed.(It stopped at 97% but I can let it continues to finish the rest because I used  UCbrowser app to download it.
