### ISSUE TITLE
Extract clusters from aggregated loom

### ISSUE THREAD

**Issue by mperalc** [linnarsson-lab/adult-human-brain#6]
Thanks very much for this resource, it is very useful. 
I'm not very familiar with the loom format and after looking at the aggregate loom object (genes x clusters) I can't seem to find the cluster names. Could you let me know how to extract this information?
Thanks again.

**Comment by rmd13** [comment]
This is stored in a excel file inside this repo.
cluster_annotation.xlsx.
You need to add this table into the loom file as scalar data (float or string of variable length) by your favirote hdf5 programming languages. I have done this today.

**Comment by mperalc** [comment]
Thanks!
