### ISSUE TITLE
Possible mismatch in google drive h5ad file and CellXGene h5ad

### ISSUE THREAD

**Issue by jzleea** [linnarsson-lab/adult-human-brain#7]
Hi Linnarsson lab
Thanks for this large body of work. I was reviewing the google drive linked h5ad files and I couldn't get the annotations to match what I also downloaded in h5ad format from the CellXGene resource. It is almost as if the neuron file and non-neuron file had some annotations swapped. Tsne and UMAP coordinates appear to match the papers though.

Data obtained from CellXGene (Non-neuron supercluster)
![image](https://user-images.githubusercontent.com/109107994/220464721-84345eea-2d89-452a-92f6-155dd0d1c814.png)

Data obtained from google drive (Nonneuron.h5ad)
![image](https://user-images.githubusercontent.com/109107994/220465074-b3287122-af49-49b6-9a76-c113c8909e31.png)

Could someone confirm for me this is the case? Thanks!
Jackson

**Comment by simonmfr** [comment]
Same issue for me @jzleea

**Comment by jdime** [comment]
Same issue for me @jzleea.

**Comment by slinnarsson** [comment]
Hi & thanks for noticing. I'll look into it and figure out what's wrong. Neither look like "tissue IDs" but rather like supercluster labels.

**Comment by pl-ki** [comment]
There was a mistake in the mapping of cellId to clusterId in the file on google drive. Thanks for pointing this out.
